### ISSUE TITLE
What about adding some spring couplets, scrolls?

### ISSUE THREAD

**Issue by ruhuasiyu** [574448121/ChineseWorkshop#10]
加点春联横幅如何？可自定义文字的那种？

**Comment by 3TUSK** [comment]
@ruhuasiyu 这是一个技术难题。

@TeamCovertDragon 的 SpringFestival 在最开始开发的时候对这个问题进行了反复讨论，最终总结了下列几点：

  1. 如果要自定义文字，那么就有必要使用某种书法字体。目前在网上找不到可以捆绑在 Mod 里一并发布的字体资源。
  2. 退一步讲，如果牺牲书法字体的效果，转而使用 Minecraft 自带的~~不知道哪里弄的~~字体，下一个问题就是“该不该把字渲染像旗帜图案一样，渲染在春联的表面”。如果要这么做，那么怎样才能让它看起来更真实？
  3. 再退一步，我们放弃让它渲染字符，那这样的春联就不太 immersive 了。
  4. 再退一步就是放弃春联自定义文字了。

我们甚至考虑过实现玩家自己写字的书法系统，没错就是玩家自己磨墨然后用毛笔写字的系统，[然而这个系统基本上是... 坑了][ref-1]。

> 如果 GitHub 的 @ 组织的功能把成员也全 @ 上了，尚祈见谅。

[ref-1]: https://github.com/TeamCovertDragon/SpringFestival/tree/master/src/main/java/team/covertdragon/springfestival/module/calligraphy

**Comment by ruhuasiyu** [comment]
@3TUSK ok，我去那边反馈
