### ISSUE TITLE
[1.14.3] Crash on startup. RuntimeException: One of more entry values did not copy to the correct id. Check log for details!

### ISSUE THREAD

**Issue by ProsperCraft** [574448121/ChineseWorkshop#11]
Crash report- 
https://gist.github.com/ProsperCraft/d9627b1e8de4788a46bfc8ea467b158e

[debug.log](https://github.com/574448121/ChineseWorkshop/files/3387559/debug.log)
[latest.log](https://github.com/574448121/ChineseWorkshop/files/3387560/latest.log)

ChineseWorkshop-1.14.3-2.0.0
forge-1.14.3-27.0.50

**Comment by Snownee** [comment]
Please try running with ChineseWorkshop and Kiwi only and see what happens

**Comment by ProsperCraft** [comment]
No crash.

**Comment by Snownee** [comment]
Would you mind sending me your pack? Twitch refuses to work on my computer? You can [join my discord server](https://www.patreon.com/snownee).

**Comment by ProsperCraft** [comment]
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

I include a tutorial on how to fix the Twitch launcher if you want to try it.

**Comment by Snownee** [comment]
Not this problem. I cannot download all mods from Twitch
