### ISSUE TITLE
[1.14.3] Unable to log in with this update - ChineseWorkshop-1.14.3-2.2.2.jar

### ISSUE THREAD

**Issue by ProsperCraft** [574448121/ChineseWorkshop#12]
Unable to log in to a dedicated server with this mod after it updated-

![693788b62beeb6b9e85af29a15281dc7](https://user-images.githubusercontent.com/4427684/61479981-3306b200-a952-11e9-86fd-bf0b2f681dbc.png)

**Comment by ProsperCraft** [comment]
Once I disabled the mod I was able to log in.

**Comment by Snownee** [comment]
Have you figured out #11?

**Comment by Snownee** [comment]
What version did you update from?

**Comment by ProsperCraft** [comment]
ChineseWorkshop-1.14.3-2.2.1.jar has the same issue.

**Comment by ProsperCraft** [comment]
Upgraded from  -ChineseWorkshop-1.14.3-2.1.0.jar

**Comment by Snownee** [comment]
Have you figured out #11?

**Comment by Snownee** [comment]
Fixed. Please update Kiwi

https://www.curseforge.com/minecraft/mc-mods/kiwi/files/2743759

**Comment by ProsperCraft** [comment]
Verified fixed.
