### ISSUE TITLE
Does not work with latest Kiwi mod.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [574448121/ChineseWorkshop#24]
![image](https://user-images.githubusercontent.com/10351221/84095071-e8f04a00-a9c3-11ea-8105-77b02e7361cc.png)

https://gist.github.com/P3rf3ctXZer0/9c303fd8a2b250adf4a8d91088986d03

**Comment by P3rf3ctXZer0** [comment]
![image](https://user-images.githubusercontent.com/10351221/84095248-72078100-a9c4-11ea-912f-d81dd03fff72.png)
Downgrading fixes crash.

**Comment by Snownee** [comment]
Thank you for reporting! here is the new one: https://www.curseforge.com/minecraft/mc-mods/chineseworkshop/files/2975873
