### ISSUE TITLE
Issue with player reconnection if he disconnected when he was seat on a chair

### ISSUE THREAD

**Issue by solarblindfull** [574448121/ChineseWorkshop#25]
Hello ! Thank for this very good mod ! Unfortunately, if a player quit the server while sitting on a chair and if the server restart, he cannot reconnect again because of a very long "loading terrain". Can you see what's wrong please ?

The server log say only that : "[net.minecraft.entity.EntityType/]: Skipping Entity with id chineseworkshop:seat".

Thank very much.

**Comment by Snownee** [comment]
I hope it has been fixed in this update

**Comment by solarblindfull** [comment]
Thank very much
