### ISSUE TITLE
Server crashing after adding just your mod. 

### ISSUE THREAD

**Issue by OldManCraft** [574448121/ChineseWorkshop#6]
Forge 2709
[Issue.txt](https://github.com/574448121/ChineseWorkshop/files/2126177/Issue.txt)

Let me know if you need anything else.

**Comment by Snownee** [comment]
Could you provide a full version of the crash report?

**Comment by Jack-0-Spades** [comment]
I have the same problem.
[crash-2018-06-22_01.49.56-server.txt](https://github.com/574448121/ChineseWorkshop/files/2126495/crash-2018-06-22_01.49.56-server.txt)
 attached the crash report

**Comment by Snownee** [comment]
@Jack-0-Spades I will look into it. Thanks!

**Comment by OldManCraft** [comment]
Why Close

**Comment by Snownee** [comment]
@OldManCraft A fix has been uploaded but is still under review.

**Comment by Jack-0-Spades** [comment]
Could you let us know when the fix is live?

**Comment by OldManCraft** [comment]
The fix is out

Tom

**Comment by Jack-0-Spades** [comment]
Thanks
