### ISSUE TITLE
Block models

### ISSUE THREAD

**Issue by Zaknafen** [574448121/ChineseWorkshop#7]
Hello,

First of all, let me tell you that I really love this mod it has been something I have wanted for a long time.  

Now on to the issue... When you create the base item for the roof pieces and use the Lalt key and scroll to a different model and then place the piece it reverts back to the original shape.  It does it for each of the base roof models.  The only way I have found to get around this is to go into cheat mode and give yourself each piece you want, place them and then the next piece until you are done.  This would be fine but I play on a server and don't have access to cheat mode.  Not sure if this is something that you can fix with the bounding boxes and all, but when you place your window in an area made of your thin walls the window does not connect to the sides just each other making a center window with gaps on both sides(4 long thin walls 2 high on the end and windows inside). 

I also have a request for your mode, is there anyway that you can integrate the different woods from Natura or Bennies (the Bee Mod) not that there is anything wrong with the white gray and oak at all I would just like to use Ebony from the bee mod in place of the oak in several places.  Can you add other materials to be made into your fence model such as your white gray wall, can you add a wall made from the black clay you added, and if you could make a model of your doors that slide like a shoji door does.

Thank you very much for taking the time to read this I hope to see more improvements to the Chineseworkshop in the future.

**Comment by Snownee** [comment]
Hey, Zaknafen!
Thanks for your suggestions! Next time I suggest you reporting in separate issues.

For your first issue, yes I have noticed and fixed the first desync problem but sadly our project owner @574448121 is too busy to upload the new file these days. But you can still download the fix [here](https://github.com/574448121/ChineseWorkshop/releases/tag/1.2.2).

Integrating different woods is already in plan, but it need time to implement. And of course we will continuously add new blocks, I think @574448121 will consider your advice.

I really like your idea about shoji door. Have you tried [MalisisDoors](https://minecraft.curseforge.com/projects/malisisdoors)? I think that will meet your need.

Cheers!

**Comment by Snownee** [comment]
> Not sure if this is something that you can fix with the bounding boxes and all, but when you place your window in an area made of your thin walls the window does not connect to the sides just each other making a center window with gaps on both sides(4 long thin walls 2 high on the end and windows inside).

Could you give a picture to describe this? Sorry I don't understand what you mean.

**Comment by Zaknafen** [comment]
![image](https://user-images.githubusercontent.com/18354470/41974827-a2c89f62-79de-11e8-88af-1e82ffdd1a4b.png)
Here is a screen shot of the window issue

**Comment by Snownee** [comment]
OK I understand. I will fix it.

**Comment by Snownee** [comment]
Implemented & will be implemented in Minecraft 1.14. Now you can replace frame of tile by crafting. And this feature can be fully disabled in the configuration. I plan to add more supports in the future.
